services:
  app:
    image: titanmen/devops-engineer-from-scratch-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    command: make test

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
