FROM node:26

RUN npm install -g pnpm@11.24.0

WORKDIR /app

# Важно для кеширования слоев
COPY app/package.json package.json
COPY app/pnpm-lock.yaml pnpm-lock.yaml
COPY app/pnpm-workspace.yaml pnpm-workspace.yaml

RUN pnpm install --frozen-lockfile

COPY app/. .

EXPOSE 8080
ENV NODE_ENV=production
RUN pnpm run build

RUN chown -R node:node /app
USER node

CMD ["make", "start"]
